#! /bin/bash
sh null/workspace/GuidedTesting/scripts/scriptStart.sh
rm -r null/workspace/GuidedTesting/wget/olduc/UCWget 
 mkdir null/workspace/GuidedTesting/wget/olduc/UCWget
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=login&Password=admin&ret_page=&FormName=Login' http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=guest&querystring=&FormAction=login&Password=guest&ret_page=Default.jsp&FormName=Login' http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=login&Password=123&ret_page=&FormName=Login' http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=login&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=login&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=sendRedirect&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=sendRedirect&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=logout&Password=123&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=logout&Password=123&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=sendRedirect&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=sendRedirect&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=login&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=login&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=sendRedirect&Password=123&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=sendRedirect&Password=123&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=logout&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=logout&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=login&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=login&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=logout&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=logout&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=sendRedirect&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=sendRedirect&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=sendRedirect&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=sendRedirect&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=login&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=login&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=logout&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=logout&Password=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=guest&querystring=&FormAction=logout&Password=guest&ret_page=Default.jsp&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=guest&querystring=&FormAction=logout&Password=guest&ret_page=Default.jsp&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=login&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=login&ret_page=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=logout&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=logout&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=sendRedirect&Password=admin&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=sendRedirect&Password=admin&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=logout&Password=admin&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=admin&querystring=&FormAction=logout&Password=admin&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=login&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=login&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=logout&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=logout&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=sendRedirect&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&querystring=&FormAction=sendRedirect&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=guest&querystring=&FormAction=sendRedirect&Password=guest&ret_page=Default.jsp&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=guest&querystring=&FormAction=sendRedirect&Password=guest&ret_page=Default.jsp&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'Login=&FormAction=sendRedirect&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'Login=&FormAction=sendRedirect&Password=&FormName=Login' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget --keep-session-cookies --save-cookies cookies.txt --post-data 'querystring=&FormAction=logout&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/wget/olduc/UCWget  --load-cookies cookies.txt --post-data 'querystring=&FormAction=logout&ret_page=&FormName=sendRedirect' http://localhost:8080 http://localhost:8080/bookstore/Login.jsp
wget --directory-prefix null/workspace/GuidedTesting/restartwget http://localhost:8080/null/Restart.jsp
cd null/Downloads/cobertura
 ./cobertura-merge.sh /var/lib/tomcat6/cobertura.ser /tmp/cobertura/sb-initial-null.ser --datafile null/null/cobertura.ser
./cobertura-report.sh --datafile null/null/cobertura.ser --destination  null/workspace/GuidedTesting/usecases/olduc/reports-null/ null/null/src
./cobertura-report.sh --format xml --datafile null/null/cobertura.ser --destination  null/workspace/GuidedTesting/usecases/olduc/reports-null/ null/null/src
rm -r null/workspace/GuidedTesting/restartwget 
 mkdir null/workspace/GuidedTesting/restartwget
